# In your generated project, open `{{ project_slug }}/api/urls.py`
# Replace its entire content with the following:

from django.urls import include, path
from rest_framework.routers import DefaultRouter

# Import the CarViewSet directly from its views file
from .cars.views import CarViewSet

# Create a single DefaultRouter for the entire API app
api_router = DefaultRouter()
# Register the CarViewSet under the 'cars' prefix for this router
api_router.register(r"cars", CarViewSet, basename="car")

# If you had other viewsets from other modules (e.g., users, products),
# you would import them and register them here:
# from .other_module.views import OtherViewSet
# api_router.register(r'other-stuff', OtherViewSet, basename='other-stuff')

urlpatterns = [
    # Include all URLs generated by the api_router at the root of the 'api' path
    # (i.e., /api/cars/, /api/cars/{id}/ etc.)
    path("", include(api_router.urls)),
]
