repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.2 # Use the latest ruff pre-commit hook release
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: run-django-tests
        name: Run Django Tests
        entry: bash -c "python manage.py test --failfast"
        language: system
        pass_filenames: false
        types: [python]
        always_run: true # Always run tests on commit
